image: gitpod/workspace-postgres

ports:
  - port: 8001
    onOpen: ignore
    visibility: private
  - port: 6379
    onOpen: ignore
    visibility: private
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 3001
    visibility: public
    onOpen: ignore
  - port: 4000
    visibility: public
    onOpen: open-browser
  - port: 4001
    visibility: public
    onOpen: ignore
  - port: 5432
    onOpen: ignore

tasks:
  - name: Start Redis Stack
    init: |
     docker-compose pull
    command: |
     alias redis-cli="docker exec -it redis-stack redis-cli" 
     echo "Use redis-cli to interact with Redis here."
     docker-compose up -d
     gp sync-done finished
    openMode: tab-after
    
  - name: Start Postgres Stack
    init: |
     psql -h localhost -U gitpod -f sql/start.sql
    openMode: tab-after
    
  - name: Start Login Stack
    init: | 
     npm run install:client
     npm run install:login
    command: npm run start:login
    openMode: tab-after
    env:
      PORT: 3000
      POSTGRES: postgres://gitpod@localhost/bombermanos

  - name: Start Game Stack
    init: | 
     npm run install:game
    command: npm run start:game
    openMode: tab-after
    env:
      PORT: 4000
      POSTGRES: postgres://gitpod@localhost/bombermanos
github: 
  prebuilds:
    master: true
    branches: true
    pullRequests: true